exports.types = {
	"css":"text/css",
	"gif":"image/gif",
	"html":"text/html",
	"ico":"image/x-icon",
	"jpeg":"image/jpeg",
	"jpg":"image/jpeg",
	"js":"text/javascripts",
	"json":"application/json",
	"pdf":"application/pdf",
	"png":"image/png",
	"svg":"image/svg",
	"swf":"application/x-shockwave-falsh",
	"tiff":"image/tiff",
	"wav":"audio/x-wav",
	"wma":"audio/x-ms-wma",
	"wmv":"audio/x-ms-wmv",
	"xml":"text/xml"
}
